[device]
channels = 8
# sampling rate of the device
sampling_rate = 200
# amount of data to acquire in each update
# read_length = 0.005   
read_length = 0.05

[stimulator]
# the name of the device to connect to
device_name = USB Serial
# hardcoding port overrides detection by name 
port =

[filter]
# window size
win_size = 0.75

[normalisation]
# normalise if more than this percentage variance
normalise_perc = 0.1
# minimum range go down to
y_range_min = 0.1
# default scaling to start with
y_range_default = 1.5
# max range is max range of analog inputs
y_range_max = 5
# how much to increment when manually scaling
y_range_increment = 0.1

[display]
# length of the scope display window in seconds
win_size = 10
# ratio of display updates to reads
update_read_ratio = 1
# columns to display traces in
columns = 4

[interface]
xy_origin = 0., -0.9
xy_scale = 1.75
rotation = 45
theta_target = 22.5

[experiment]
subject = MD
# control channels (1 based)
channels = 5,8
# number of trials
n_trials = 12
# number of targets
n_targets = 4
# length of isi
trial_interval = 2.
# length of reach period
reach =1.5
# length of hold period
hold =1.5
# length of score displayed for
score_present = 1.
# length of rest
win_size_rest = 0.2

